package net.foodeals.offer.domain.enums;

public enum Category {
	// Categories for Bakeries / Pastries
	BREAD_AND_PASTRIES(PublishAs.BAKERIES_PASTRIES), PASTRIES(PublishAs.BAKERIES_PASTRIES),
	CAKES(PublishAs.BAKERIES_PASTRIES), SMALL_PASTRIES(PublishAs.BAKERIES_PASTRIES),
	SAVORY_PRODUCTS(PublishAs.BAKERIES_PASTRIES),

	// Categories for Supermarkets / Hypermarkets
	FRUITS_AND_VEGETABLES(PublishAs.SUPERMARKETS_HYPERMARKETS), MEAT_AND_FISH(PublishAs.SUPERMARKETS_HYPERMARKETS),
	BISCUITS_AND_CONFECTIONERY(PublishAs.SUPERMARKETS_HYPERMARKETS), DAIRY_PRODUCTS(PublishAs.SUPERMARKETS_HYPERMARKETS),
	CEREAL_PRODUCTS(PublishAs.SUPERMARKETS_HYPERMARKETS), CANNED_PRODUCTS(PublishAs.SUPERMARKETS_HYPERMARKETS),
	FROZEN_PRODUCTS(PublishAs.SUPERMARKETS_HYPERMARKETS), GROCERY_PRODUCTS(PublishAs.SUPERMARKETS_HYPERMARKETS),
	WATER_AND_BEVERAGES(PublishAs.SUPERMARKETS_HYPERMARKETS),

	// Categories for Restaurants / Hotels / Caterers
	FAST_FOOD(PublishAs.RESTAURANTS_HOTELS_CATERERS), DISHES(PublishAs.RESTAURANTS_HOTELS_CATERERS),
	ASIAN(PublishAs.RESTAURANTS_HOTELS_CATERERS), SALADS(PublishAs.RESTAURANTS_HOTELS_CATERERS),
	DESSERTS(PublishAs.RESTAURANTS_HOTELS_CATERERS),

	// Categories for Wholesalers and Industrial
	WHOLESALER_FRUITS_AND_VEGETABLES(PublishAs.WHOLESALERS_INDUSTRIALS),
	WHOLESALER_BISCUITS_AND_CONFECTIONERY(PublishAs.WHOLESALERS_INDUSTRIALS),
	WHOLESALER_DAIRY_PRODUCTS(PublishAs.WHOLESALERS_INDUSTRIALS),
	WHOLESALER_DRY_PRODUCTS(PublishAs.WHOLESALERS_INDUSTRIALS),
	WHOLESALER_CANNED_PRODUCTS(PublishAs.WHOLESALERS_INDUSTRIALS),
	WHOLESALER_FROZEN_PRODUCTS(PublishAs.WHOLESALERS_INDUSTRIALS),
	WHOLESALER_GROCERY_PRODUCTS(PublishAs.WHOLESALERS_INDUSTRIALS),
	WHOLESALER_BEVERAGES(PublishAs.WHOLESALERS_INDUSTRIALS);

	private final PublishAs publishAs;

	Category(PublishAs publishAs) {
		this.publishAs = publishAs;
	}

	public PublishAs getDealType() {
		return publishAs;
	}
}
